function DIDrho     =  SensitityOptimisationLinearised(x_elem,x_elem_n,X_elem,DNX,IntWeight,mat_parameters,...
                             p_elem,Klinear,void_factor,diff_void_factor,...
                             rho_p,diff_rho_p,rho_linear,diff_rho_linear)


