%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%
%  This function adds the contribution of the solid and the void to the
%  first and second derivatives of the constitutive model
%
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------

function derivatives     =  SumDerivativesU(derivatives,derivatives_void,...
                                            rho,penal,aux)
                                         
                                         
derivatives.DU.DUDF      =  (rho^penal)*derivatives.DU.DUDF + ...
                            (aux - rho^penal)*derivatives_void.DU.DUDF;                                          
derivatives.DU.DUDH      =  (rho^penal)*derivatives.DU.DUDH + ...
                            (aux - rho^penal)*derivatives_void.DU.DUDH;                                          
derivatives.DU.DUDJ      =  (rho^penal)*derivatives.DU.DUDJ + ...
                            (aux - rho^penal)*derivatives_void.DU.DUDJ;                                          

derivatives.D2U.D2UDFDF  =  (rho^penal)*derivatives.D2U.D2UDFDF + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDFDF;                                                                  
derivatives.D2U.D2UDFDH  =  (rho^penal)*derivatives.D2U.D2UDFDH + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDFDH;                                                                  
derivatives.D2U.D2UDFDJ  =  (rho^penal)*derivatives.D2U.D2UDFDJ + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDFDJ;                                                                  

derivatives.D2U.D2UDHDF  =  (rho^penal)*derivatives.D2U.D2UDHDF + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDHDF;                                                                  
derivatives.D2U.D2UDHDH  =  (rho^penal)*derivatives.D2U.D2UDHDH + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDHDH;                                                                  
derivatives.D2U.D2UDHDJ  =  (rho^penal)*derivatives.D2U.D2UDHDJ + ...
                            (aux - rho^penal)*derivatives_void.D2U.D2UDHDJ;                                                                  

derivatives.D2U.D2UDJDF  =  (rho^penal)*derivatives.D2U.D2UDJDF + ...
                            (1 - rho^penal)*derivatives_void.D2U.D2UDJDF;                                                                  
derivatives.D2U.D2UDJDH  =  (rho^penal)*derivatives.D2U.D2UDJDH + ...
                            (1 - rho^penal)*derivatives_void.D2U.D2UDJDH;                                                                  
derivatives.D2U.D2UDJDJ  =  (rho^penal)*derivatives.D2U.D2UDJDJ + ...
                            (1 - rho^penal)*derivatives_void.D2U.D2UDJDJ;                                                                  
                        
                        