gcc ParentGradientsMexC.c -o ParentGradientsMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc WeightsIntegrationMexC.c -o WeightsIntegrationMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc KinematicsMexC.c -o KinematicsMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinModelMexC.cpp -o MooneyRivlinModelMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
g++ FirstPiolaMexC.cpp -o FirstPiolaMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc BmatricesMexC.c -o BmatricesMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc StiffnessMatrixUFormulation.c -o StiffnessMatrixUFormulation.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG



gcc ParentGradientsMexC.c -o ParentGradientsMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc WeightsIntegrationMexC.c -o WeightsIntegrationMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc KinematicsCMexC.c -o KinematicsCMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinModelCMexC.cpp -o MooneyRivlinModelCMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc BmatricesCMexC.c -o BmatricesCMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc GeometricStiffnessCMexC.c -o GeometricStiffnessCMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc StiffnessMatricesDBCMexC.c -o StiffnessMatricesDBCMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


gcc KinematicsFinalMexC.c -o KinematicsFinalMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinModelFbasedMexC.cpp -o MooneyRivlinModelFbasedMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc TangentOperatorUFormulationMexC.c -o TangentOperatorUFormulationMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


gcc KinematicsFunctionLinearisedMexC.c -o KinematicsFunctionLinearisedMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinLinearisedMexC.cpp -o MooneyRivlinLinearisedMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc KinematicsFunctionConvexifiedMexC.c -o KinematicsFunctionConvexifiedMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinConvexifiedMexC.cpp -o MooneyRivlinConvexifiedMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc SylvesterCriterionElasticity.c -o SylvesterCriterionElasticity.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OPTIMISATION_CODE\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG

gcc RegularisationElasticity1MexC.c -o RegularisationElasticity1MexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc CheckSylvester.c -o CheckSylvester.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\m" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


g++ MooneyRivlinMexC.cpp -o MooneyRivlinMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc TangentOperatorUFormulationMexC.c -o TangentOperatorUFormulationMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


gcc RegularisationElasticity1MexC.c -o RegularisationElasticity1MexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


gcc CheckTensorAlgebra.c -o CheckTensorAlgebra.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc CorrectedMooneyRivlin.c -o CorrectedMooneyRivlin.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinExplicitMexC.cpp -o MooneyRivlinExplicitMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14




gcc CheckMinors.c -o CheckMinors.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc RegularisationElasticity1MexC.c -o RegularisationElasticity1MexC1.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
g++ MooneyRivlinPlaneStress.cpp -o MooneyRivlinPlaneStress.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
gcc RegularisationElasticity2MexC.c -o RegularisationElasticity2MexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG



gcc SylvesterCriterionElasticity2.c -o SylvesterCriterionElasticity2.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc RegularisationElasticity1MexC.c -o RegularisationElasticity1MexC_.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG

gcc CheckMinors.c -o CheckMinors.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG
gcc MooneyRivlinEnergyMexC.c -o MooneyRivlinEnergyMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG


g++ MooneyRivlinPlaneStress.cpp -o MooneyRivlinPlaneStress.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14
g++ MooneyRivlinTransverseIsotropyTensionMexC.cpp -o MooneyRivlinTransverseIsotropyTensionMexC.mexw64 -shared -I"C:\Program Files\MATLAB\R2015b\extern\include" -I"C:\SoftwareDevelopment\OptimisationProjectCiudadReal\code\include" -L"C:\Program Files\MATLAB\R2015b\bin\win64" -lmex -lmat -leng -lmx -L"C:\Program Files\MATLAB\R2015b\extern\lib\win64\mingw64" -lmwblas -O3 -march=native -DNDEBUG -I"C:\SoftwareDevelopment\Fastor-master" -std=c++14

